version: '3.9'

services:

  db:
    image: postgres # "postgres:14.7-alpine"
    restart: always
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
