version: '3.9'

services:

  api:
    build: .
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Environment=Production
      - CustomersApi_Database__ConnectionString=Server=db;Port=5432;Database=integration_testing;User ID=course;Password=password;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14.7-alpine #postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=integration_testing
    ports:
      - '5432:5432'
